fastlane_version '2.143.0'

default_platform(:ios)

platform :ios do

  DERIVED_DATA_PATH = '/tmp/DerivedData'

  desc 'Install Cocoapods'
  lane :install do
    cocoapods(try_repo_update_on_error: true)
  end

  desc 'Compile'
  lane :build do
    build_ios_app(
      skip_archive: true,
      skip_package_ipa: true,
      output_directory: '.',
      derived_data_path: DERIVED_DATA_PATH,
      xcargs: '-allowProvisioningUpdates',
    )
  end

  desc 'Run unit and UI tests'
  lane :test do
    run_tests(
      include_simulator_logs: false,
      derived_data_path: DERIVED_DATA_PATH,
      xcargs: '-allowProvisioningUpdates',
    )
  end

  desc 'SwiftLint'
  lane :lint do
    swiftlint(
      strict: true,
      executable: 'Pods/SwiftLint/swiftlint',
    )
  end
end
