fastlane_version '2.143.0'

default_platform(:ios)

platform :ios do

  DERIVED_DATA_PATH = '/tmp/DerivedData'

  lane :install do
    cocoapods(try_repo_update_on_error: true)
  end

  lane :build do
    build_ios_app(
      skip_archive: true,
      skip_package_ipa: true,
      output_directory: '.',
      derived_data_path: DERIVED_DATA_PATH,
    )
  end

  lane :test do
    run_tests(
      include_simulator_logs: false,
      devices: ['iPhone Xs Max'],
      derived_data_path: DERIVED_DATA_PATH,
    )
  end
end
