name: CI
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CI tools
      run: bundle install
    - name: Tests
      run: bundle exec fastlane ios test
