name: CI
on:
  push:
    branches: [ master ]
jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Apollo CLI
      run: yarn install
    - name: Install Fastlane
      run: bundle install
    - name: Compile the app
      run: bundle exec fastlane ios build
    - name: Run tests
      run: bundle exec fastlane ios test
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run SwiftLint
      run: Pods/SwiftLint/swiftlint --strict
