name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: ls -hal ..
      run: ls -hal ..
    - name: ls -hal ./
      run: ls -hal ./
