name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Apollo CLI
      run: yarn install
    - name: Install Fastlane
      run: bundle install
    - name: Configure build toolchain
      run: sudo xcode-select --switch /Applications/Xcode_11.3.1.app
    - name: Compile the app
      run: bundle exec fastlane ios build
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Apollo CLI
      run: yarn install
    - name: Install Fastlane
      run: bundle install
    - name: Configure build toolchain
      run: sudo xcode-select --switch /Applications/Xcode_11.3.1.app
    - name: Run tests
      run: bundle exec fastlane ios test
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run SwiftLint
      run: Pods/SwiftLint/swiftlint --strict
