name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone Xs Max']
    steps:
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: build
        skip-tracking: true 
  test:
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone Xs Max']
    steps:
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: test
        skip-tracking: true
